/**
 * Reference profiles for known models — REAL DATA from CodeBuddy API calibration.
 *
 * Auto-generated by scripts/calibrate-codebuddy.mjs
 * Generated at: 2026-04-09T05:09:41.810Z
 *
 * Each profile is the expected MEAN and STANDARD DEVIATION for the 15 features.
 * Built by analyzing real coding responses from each model via CodeBuddy API.
 *
 * Feature order matches FEATURE_NAMES in features.mjs:
 * [responseLength, lineCount, codeBlockDensity, markdownRichness, paragraphCount, vocabRichness, avgSentenceLength, avgWordLength, longWordRatio, hedgingRate, confidenceRate, firstPersonRate, transitionRate, codeProseRatio, codeCommentDensity]
 */

export const MODEL_PROFILES = Object.freeze({
  // Calibrated from 88 real CodeBuddy responses (claude-opus-4.6)
  'claude-opus-4.6': Object.freeze({
    mean: Object.freeze([0.7785, 0.6399, 0.5212, 0.4122, 0.8403, 0.5320, 0.4593, 0.4894, 0.2048, 0.0205, 0.1453, 0.0217, 0.0000, 0.7467, 0.0795]),
    std:  Object.freeze([0.0349, 0.0572, 0.2983, 0.2753, 0.2384, 0.0836, 0.2894, 0.0763, 0.0621, 0.0559, 0.2505, 0.0735, 0.0000, 0.4081, 0.0995]),
    description: 'Calibrated from 88 real CodeBuddy responses (claude-opus-4.6)',
  }),

  // Calibrated from 100 real CodeBuddy responses (claude-opus-4.5)
  'claude-opus-4.5': Object.freeze({
    mean: Object.freeze([0.7772, 0.6495, 0.5176, 0.3941, 0.7832, 0.5247, 0.4652, 0.5026, 0.2139, 0.0231, 0.0980, 0.0243, 0.0000, 0.7264, 0.0843]),
    std:  Object.freeze([0.0279, 0.0438, 0.2822, 0.2854, 0.2317, 0.0721, 0.3078, 0.0736, 0.0610, 0.0815, 0.2351, 0.0622, 0.0000, 0.3813, 0.0811]),
    description: 'Calibrated from 100 real CodeBuddy responses (claude-opus-4.5)',
  }),

  // Calibrated from 100 real CodeBuddy responses (claude-sonnet-4.6)
  'claude-sonnet-4.6': Object.freeze({
    mean: Object.freeze([0.7820, 0.6546, 0.5699, 0.4042, 0.9132, 0.5288, 0.5015, 0.4959, 0.2060, 0.0285, 0.1654, 0.0178, 0.0000, 0.8066, 0.0647]),
    std:  Object.freeze([0.0228, 0.0380, 0.2638, 0.2586, 0.1663, 0.0633, 0.3220, 0.0782, 0.0630, 0.0827, 0.2720, 0.0654, 0.0000, 0.3488, 0.0803]),
    description: 'Calibrated from 100 real CodeBuddy responses (claude-sonnet-4.6)',
  }),

  // Calibrated from 100 real CodeBuddy responses (claude-sonnet-4.5)
  'claude-sonnet-4.5': Object.freeze({
    mean: Object.freeze([0.7713, 0.6419, 0.5659, 0.4397, 0.7226, 0.5264, 0.4559, 0.5126, 0.2224, 0.0230, 0.0902, 0.0148, 0.0000, 0.7593, 0.0991]),
    std:  Object.freeze([0.0316, 0.0495, 0.3197, 0.3394, 0.2409, 0.0802, 0.3197, 0.0748, 0.0558, 0.0754, 0.2230, 0.0482, 0.0000, 0.3977, 0.1073]),
    description: 'Calibrated from 100 real CodeBuddy responses (claude-sonnet-4.5)',
  }),

  // Calibrated from 100 real CodeBuddy responses (claude-haiku-4.5)
  'claude-haiku-4.5': Object.freeze({
    mean: Object.freeze([0.7739, 0.6493, 0.5497, 0.4822, 0.7521, 0.5264, 0.4612, 0.5134, 0.2265, 0.0186, 0.1082, 0.0151, 0.0000, 0.7721, 0.0916]),
    std:  Object.freeze([0.0315, 0.0465, 0.2781, 0.3097, 0.2393, 0.0808, 0.3329, 0.0822, 0.0670, 0.0676, 0.2360, 0.0443, 0.0000, 0.3679, 0.1021]),
    description: 'Calibrated from 100 real CodeBuddy responses (claude-haiku-4.5)',
  }),

  // Calibrated from 94 real CodeBuddy responses (gpt-5.4)
  'gpt-5.4': Object.freeze({
    mean: Object.freeze([0.7224, 0.5895, 0.3618, 0.6891, 0.7044, 0.6260, 0.4495, 0.4444, 0.1578, 0.1893, 0.1455, 0.0797, 0.0000, 0.5551, 0.0192]),
    std:  Object.freeze([0.0620, 0.0811, 0.2864, 0.3137, 0.2966, 0.0920, 0.2691, 0.0633, 0.0520, 0.2869, 0.2944, 0.1022, 0.0000, 0.4373, 0.0428]),
    description: 'Calibrated from 94 real CodeBuddy responses (gpt-5.4)',
  }),

  // Calibrated from 99 real CodeBuddy responses (gpt-5.3-codex)
  'gpt-5.3-codex': Object.freeze({
    mean: Object.freeze([0.7012, 0.5306, 0.3652, 0.5539, 0.5385, 0.7156, 0.3520, 0.4792, 0.1877, 0.1453, 0.1497, 0.0638, 0.0079, 0.5116, 0.0244]),
    std:  Object.freeze([0.0606, 0.0747, 0.3415, 0.3596, 0.2701, 0.0907, 0.2238, 0.0750, 0.0593, 0.2645, 0.3077, 0.0844, 0.0559, 0.4648, 0.0419]),
    description: 'Calibrated from 99 real CodeBuddy responses (gpt-5.3-codex)',
  }),

  // Calibrated from 99 real CodeBuddy responses (gemini-3.1-pro)
  'gemini-3.1-pro': Object.freeze({
    mean: Object.freeze([0.4995, 0.1668, 0.0040, 0.2402, 0.0271, 0.9080, 0.3294, 0.4573, 0.1903, 0.0341, 0.0303, 0.0550, 0.0101, 0.0047, 0.0000]),
    std:  Object.freeze([0.0335, 0.0729, 0.0253, 0.3049, 0.0472, 0.0769, 0.1686, 0.0764, 0.0876, 0.1757, 0.1723, 0.2190, 0.1005, 0.0303, 0.0000]),
    description: 'Calibrated from 99 real CodeBuddy responses (gemini-3.1-pro)',
  }),

  // ─── Backward-compatible aliases ─────────────────────────────────
  'claude-opus': Object.freeze({
    mean: Object.freeze([0.7785, 0.6399, 0.5212, 0.4122, 0.8403, 0.5320, 0.4593, 0.4894, 0.2048, 0.0205, 0.1453, 0.0217, 0.0000, 0.7467, 0.0795]),
    std:  Object.freeze([0.0349, 0.0572, 0.2983, 0.2753, 0.2384, 0.0836, 0.2894, 0.0763, 0.0621, 0.0559, 0.2505, 0.0735, 0.0000, 0.4081, 0.0995]),
    description: 'Alias for claude-opus-4.6',
  }),

  'claude-sonnet': Object.freeze({
    mean: Object.freeze([0.7820, 0.6546, 0.5699, 0.4042, 0.9132, 0.5288, 0.5015, 0.4959, 0.2060, 0.0285, 0.1654, 0.0178, 0.0000, 0.8066, 0.0647]),
    std:  Object.freeze([0.0228, 0.0380, 0.2638, 0.2586, 0.1663, 0.0633, 0.3220, 0.0782, 0.0630, 0.0827, 0.2720, 0.0654, 0.0000, 0.3488, 0.0803]),
    description: 'Alias for claude-sonnet-4.6',
  }),

  'claude-haiku': Object.freeze({
    mean: Object.freeze([0.7739, 0.6493, 0.5497, 0.4822, 0.7521, 0.5264, 0.4612, 0.5134, 0.2265, 0.0186, 0.1082, 0.0151, 0.0000, 0.7721, 0.0916]),
    std:  Object.freeze([0.0315, 0.0465, 0.2781, 0.3097, 0.2393, 0.0808, 0.3329, 0.0822, 0.0670, 0.0676, 0.2360, 0.0443, 0.0000, 0.3679, 0.1021]),
    description: 'Alias for claude-haiku-4.5',
  }),

  'gpt-4o': Object.freeze({
    mean: Object.freeze([0.7224, 0.5895, 0.3618, 0.6891, 0.7044, 0.6260, 0.4495, 0.4444, 0.1578, 0.1893, 0.1455, 0.0797, 0.0000, 0.5551, 0.0192]),
    std:  Object.freeze([0.0620, 0.0811, 0.2864, 0.3137, 0.2966, 0.0920, 0.2691, 0.0633, 0.0520, 0.2869, 0.2944, 0.1022, 0.0000, 0.4373, 0.0428]),
    description: 'Alias for gpt-5.4',
  }),

  // 国产模型典型特征 — placeholder until calibrated with real data
  'domestic': Object.freeze({
    mean: Object.freeze([0.4500, 0.4000, 0.3000, 0.2200, 0.3000, 0.3500, 0.4200, 0.4500, 0.2800, 0.0800, 0.2200, 0.2000, 0.1000, 0.3000, 0.1200]),
    std:  Object.freeze([0.1800, 0.2000, 0.2200, 0.1400, 0.1500, 0.1200, 0.1600, 0.0800, 0.1000, 0.0600, 0.0800, 0.1000, 0.0600, 0.2200, 0.1000]),
    description: '国产模型(Qwen/DeepSeek/GLM): 估算值，待实际校准',
  }),
});
